### ISSUE TITLE
Hello it does not work with django2.0 django-recaptcha2.0.4

### ISSUE THREAD

**Issue by anufry** [volrath/django-captcha-admin#8]
It tries to satisfy django-recaptcha1.3.0 but I am using 2.0.4 now and can not downgrade because of widgets support

ImportError: cannot import name 'ReCaptchaV2Checkbox' from 'captcha.widgets' (......env/lib/python3.7/site-packages/captcha/widgets.py)
